### ISSUE TITLE
In mobile devices, the intro logo doesn't disappear.

### ISSUE THREAD

**Issue by narnianpony** [lasseborly/forbidden-sheets#13]
![unnamed](https://user-images.githubusercontent.com/55762630/196247994-9dc26152-5213-4596-94be-dda22108a22f.png)
Hi, Amazing sheets BTW, I love using this while playing.
As you can see in the picture, In mobile devices, the intro logo doesn't disappear.
Thanks a lot for this!

**Comment by lasseborly** [comment]
I'll have a look at this today @narnianpony

I'm not able to replicate on my iOS device so I need to dig out my old android device.

**Comment by lasseborly** [comment]
This should be fixed now in the latest 0.0.26 release @narnianpony. Remember to update the app when prompted.
