### ISSUE TITLE
Printable Version

### ISSUE THREAD

**Issue by nd3v404** [lasseborly/forbidden-sheets#14]
Thank you for this fantastic tool you created. Is there any chance to have a print option, so you can store your character online but bring them to the table to play (some people still play in person^^). I experimented a bit, but not even scaling the sheet down in the printer settings yields good results. (The screenshot is 30% and as you can see the lower part is missing completely. on page 2 there's only the loading symbol)

![image](https://github.com/lasseborly/forbidden-sheets/assets/33373512/25b5b542-cb98-4811-8bbe-1b4a87bb15a2)

**Comment by lasseborly** [comment]
I'll give it a look.

**Comment by lasseborly** [comment]
Hi @nd3v404 

I have implemented a very crude work around but it should work. Forbidden Sheets was never really built for printing. Which shows. Maybe in version v3..

But try and print now and have settings that looks kinda like this:

<img width="1440" alt="image" src="https://github.com/lasseborly/forbidden-sheets/assets/2671660/75e4cc59-426c-4aaf-9589-38c5edcf5a5a">


Adjust the scaling if you are using anything else but A4.

You need "Backround graphics" on to support the red dots, if you are using those.
